name: "flutter_miracl_sdk_example_app"
description: "Example application demonstrating the usage of MIRACL Trust Flutter Plugin"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  flutter_miracl_sdk:
    path: ../
  dart_jsonwebtoken: ^3.2.0
  go_router: ^15.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  http: ^1.2.1

flutter:
  uses-material-design: true