// Autogenerated from Pigeon (v25.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsPigeon(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsPigeon(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsPigeon(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashPigeon(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashPigeon(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashPigeon(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct MConfiguration: Hashable {
  var projectId: String
  var clientId: String
  var redirectUri: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MConfiguration? {
    let projectId = pigeonVar_list[0] as! String
    let clientId = pigeonVar_list[1] as! String
    let redirectUri = pigeonVar_list[2] as! String

    return MConfiguration(
      projectId: projectId,
      clientId: clientId,
      redirectUri: redirectUri
    )
  }
  func toList() -> [Any?] {
    return [
      projectId,
      clientId,
      redirectUri,
    ]
  }
  static func == (lhs: MConfiguration, rhs: MConfiguration) -> Bool {
    return deepEqualsPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MExceptions: Hashable {
  var message: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MExceptions? {
    let message = pigeonVar_list[0] as! String

    return MExceptions(
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      message
    ]
  }
  static func == (lhs: MExceptions, rhs: MExceptions) -> Bool {
    return deepEqualsPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MActivationTokenResponse: Hashable {
  var projectId: String
  var accessId: String? = nil
  var userId: String
  var activationToken: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MActivationTokenResponse? {
    let projectId = pigeonVar_list[0] as! String
    let accessId: String? = nilOrValue(pigeonVar_list[1])
    let userId = pigeonVar_list[2] as! String
    let activationToken = pigeonVar_list[3] as! String

    return MActivationTokenResponse(
      projectId: projectId,
      accessId: accessId,
      userId: userId,
      activationToken: activationToken
    )
  }
  func toList() -> [Any?] {
    return [
      projectId,
      accessId,
      userId,
      activationToken,
    ]
  }
  static func == (lhs: MActivationTokenResponse, rhs: MActivationTokenResponse) -> Bool {
    return deepEqualsPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MAuthenticationSessionDetails: Hashable {
  var userId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MAuthenticationSessionDetails? {
    let userId = pigeonVar_list[0] as! String

    return MAuthenticationSessionDetails(
      userId: userId
    )
  }
  func toList() -> [Any?] {
    return [
      userId
    ]
  }
  static func == (lhs: MAuthenticationSessionDetails, rhs: MAuthenticationSessionDetails) -> Bool {
    return deepEqualsPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MUser: Hashable {
  var projectId: String
  var revoked: Bool
  var userId: String
  var hashedMpinId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MUser? {
    let projectId = pigeonVar_list[0] as! String
    let revoked = pigeonVar_list[1] as! Bool
    let userId = pigeonVar_list[2] as! String
    let hashedMpinId = pigeonVar_list[3] as! String

    return MUser(
      projectId: projectId,
      revoked: revoked,
      userId: userId,
      hashedMpinId: hashedMpinId
    )
  }
  func toList() -> [Any?] {
    return [
      projectId,
      revoked,
      userId,
      hashedMpinId,
    ]
  }
  static func == (lhs: MUser, rhs: MUser) -> Bool {
    return deepEqualsPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MQuickCode: Hashable {
  var code: String
  var expiryTime: Int64
  var ttlSeconds: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MQuickCode? {
    let code = pigeonVar_list[0] as! String
    let expiryTime = pigeonVar_list[1] as! Int64
    let ttlSeconds = pigeonVar_list[2] as! Int64

    return MQuickCode(
      code: code,
      expiryTime: expiryTime,
      ttlSeconds: ttlSeconds
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      expiryTime,
      ttlSeconds,
    ]
  }
  static func == (lhs: MQuickCode, rhs: MQuickCode) -> Bool {
    return deepEqualsPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MSignature: Hashable {
  var u: String
  var v: String
  var dtas: String
  var mpinId: String
  var hash: String
  var publicKey: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MSignature? {
    let u = pigeonVar_list[0] as! String
    let v = pigeonVar_list[1] as! String
    let dtas = pigeonVar_list[2] as! String
    let mpinId = pigeonVar_list[3] as! String
    let hash = pigeonVar_list[4] as! String
    let publicKey = pigeonVar_list[5] as! String

    return MSignature(
      u: u,
      v: v,
      dtas: dtas,
      mpinId: mpinId,
      hash: hash,
      publicKey: publicKey
    )
  }
  func toList() -> [Any?] {
    return [
      u,
      v,
      dtas,
      mpinId,
      hash,
      publicKey,
    ]
  }
  static func == (lhs: MSignature, rhs: MSignature) -> Bool {
    return deepEqualsPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MSigningResult: Hashable {
  var signature: MSignature
  var timestamp: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MSigningResult? {
    let signature = pigeonVar_list[0] as! MSignature
    let timestamp = pigeonVar_list[1] as! Int64

    return MSigningResult(
      signature: signature,
      timestamp: timestamp
    )
  }
  func toList() -> [Any?] {
    return [
      signature,
      timestamp,
    ]
  }
  static func == (lhs: MSigningResult, rhs: MSigningResult) -> Bool {
    return deepEqualsPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeon(value: toList(), hasher: &hasher)
  }
}

private class PigeonPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return MConfiguration.fromList(self.readValue() as! [Any?])
    case 130:
      return MExceptions.fromList(self.readValue() as! [Any?])
    case 131:
      return MActivationTokenResponse.fromList(self.readValue() as! [Any?])
    case 132:
      return MAuthenticationSessionDetails.fromList(self.readValue() as! [Any?])
    case 133:
      return MUser.fromList(self.readValue() as! [Any?])
    case 134:
      return MQuickCode.fromList(self.readValue() as! [Any?])
    case 135:
      return MSignature.fromList(self.readValue() as! [Any?])
    case 136:
      return MSigningResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PigeonPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? MConfiguration {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? MExceptions {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? MActivationTokenResponse {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? MAuthenticationSessionDetails {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? MUser {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? MQuickCode {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? MSignature {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? MSigningResult {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PigeonPigeonCodecWriter(data: data)
  }
}

class PigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PigeonPigeonCodec(readerWriter: PigeonPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MiraclSdk {
  func initSdk(configuration: MConfiguration, completion: @escaping (Result<Void, Error>) -> Void)
  func sendVerificationEmail(userId: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func getActivationToken(uri: String, completion: @escaping (Result<MActivationTokenResponse, Error>) -> Void)
  func getUsers(completion: @escaping (Result<[MUser], Error>) -> Void)
  func register(userId: String, activationToken: String, pin: String, pushToken: String?, completion: @escaping (Result<MUser, Error>) -> Void)
  func authenticate(user: MUser, pin: String, completion: @escaping (Result<String, Error>) -> Void)
  func getAuthenticationSessionDetailsFromQRCode(qrCode: String, completion: @escaping (Result<MAuthenticationSessionDetails, Error>) -> Void)
  func delete(userId: String, completion: @escaping (Result<Void, Error>) -> Void)
  func generateQuickCode(userId: String, pin: String, completion: @escaping (Result<MQuickCode, Error>) -> Void)
  func sign(userId: String, pin: String, message: FlutterStandardTypedData, completion: @escaping (Result<MSigningResult, Error>) -> Void)
  func authenticateWithQrCode(userId: String, pin: String, qrCode: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func authenticateWithNotificationPayload(payload: [String: String], pin: String, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MiraclSdkSetup {
  static var codec: FlutterStandardMessageCodec { PigeonPigeonCodec.shared }
  /// Sets up an instance of `MiraclSdk` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MiraclSdk?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initSdkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_miracl_sdk.MiraclSdk.initSdk\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initSdkChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configurationArg = args[0] as! MConfiguration
        api.initSdk(configuration: configurationArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initSdkChannel.setMessageHandler(nil)
    }
    let sendVerificationEmailChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_miracl_sdk.MiraclSdk.sendVerificationEmail\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendVerificationEmailChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let userIdArg = args[0] as! String
        api.sendVerificationEmail(userId: userIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendVerificationEmailChannel.setMessageHandler(nil)
    }
    let getActivationTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_miracl_sdk.MiraclSdk.getActivationToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getActivationTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let uriArg = args[0] as! String
        api.getActivationToken(uri: uriArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getActivationTokenChannel.setMessageHandler(nil)
    }
    let getUsersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_miracl_sdk.MiraclSdk.getUsers\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getUsersChannel.setMessageHandler { _, reply in
        api.getUsers { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getUsersChannel.setMessageHandler(nil)
    }
    let registerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_miracl_sdk.MiraclSdk.register\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      registerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let userIdArg = args[0] as! String
        let activationTokenArg = args[1] as! String
        let pinArg = args[2] as! String
        let pushTokenArg: String? = nilOrValue(args[3])
        api.register(userId: userIdArg, activationToken: activationTokenArg, pin: pinArg, pushToken: pushTokenArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      registerChannel.setMessageHandler(nil)
    }
    let authenticateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_miracl_sdk.MiraclSdk.authenticate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      authenticateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let userArg = args[0] as! MUser
        let pinArg = args[1] as! String
        api.authenticate(user: userArg, pin: pinArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      authenticateChannel.setMessageHandler(nil)
    }
    let getAuthenticationSessionDetailsFromQRCodeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_miracl_sdk.MiraclSdk.getAuthenticationSessionDetailsFromQRCode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAuthenticationSessionDetailsFromQRCodeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let qrCodeArg = args[0] as! String
        api.getAuthenticationSessionDetailsFromQRCode(qrCode: qrCodeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getAuthenticationSessionDetailsFromQRCodeChannel.setMessageHandler(nil)
    }
    let deleteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_miracl_sdk.MiraclSdk.delete\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let userIdArg = args[0] as! String
        api.delete(userId: userIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      deleteChannel.setMessageHandler(nil)
    }
    let generateQuickCodeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_miracl_sdk.MiraclSdk.generateQuickCode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateQuickCodeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let userIdArg = args[0] as! String
        let pinArg = args[1] as! String
        api.generateQuickCode(userId: userIdArg, pin: pinArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateQuickCodeChannel.setMessageHandler(nil)
    }
    let signChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_miracl_sdk.MiraclSdk.sign\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      signChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let userIdArg = args[0] as! String
        let pinArg = args[1] as! String
        let messageArg = args[2] as! FlutterStandardTypedData
        api.sign(userId: userIdArg, pin: pinArg, message: messageArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      signChannel.setMessageHandler(nil)
    }
    let authenticateWithQrCodeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_miracl_sdk.MiraclSdk.authenticateWithQrCode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      authenticateWithQrCodeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let userIdArg = args[0] as! String
        let pinArg = args[1] as! String
        let qrCodeArg = args[2] as! String
        api.authenticateWithQrCode(userId: userIdArg, pin: pinArg, qrCode: qrCodeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      authenticateWithQrCodeChannel.setMessageHandler(nil)
    }
    let authenticateWithNotificationPayloadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_miracl_sdk.MiraclSdk.authenticateWithNotificationPayload\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      authenticateWithNotificationPayloadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let payloadArg = args[0] as! [String: String]
        let pinArg = args[1] as! String
        api.authenticateWithNotificationPayload(payload: payloadArg, pin: pinArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      authenticateWithNotificationPayloadChannel.setMessageHandler(nil)
    }
  }
}
