#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
#ifndef MIRACLTRUST_SWIFT_H
#define MIRACLTRUST_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="MIRACLTrust",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSString;

/// The response returned from <a href="x-source-tag://miracltrust-_FUNC_getActivationTokenverificationurlcompletionHandler">getActivationToken</a>
/// when there is an error in the request.
SWIFT_CLASS("_TtC11MIRACLTrust28ActivationTokenErrorResponse")
@interface ActivationTokenErrorResponse : NSObject
@property (nonatomic, copy) NSString * _Nonnull projectId;
@property (nonatomic, copy) NSString * _Nonnull error;
@property (nonatomic, copy) NSString * _Nonnull userId;
@property (nonatomic, copy) NSString * _Nullable accessId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11MIRACLTrust23ActivationTokenResponse")
@interface ActivationTokenResponse : NSObject
/// The activation token returned after successful user verification.
@property (nonatomic, copy) NSString * _Nonnull activationToken;
@property (nonatomic, copy) NSString * _Nonnull projectId;
@property (nonatomic, copy) NSString * _Nonnull userId;
@property (nonatomic, copy) NSString * _Nullable accessId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum VerificationMethod : NSInteger;
enum IdentityType : NSInteger;

/// Object representing details from incoming session.
SWIFT_CLASS("_TtC11MIRACLTrust14SessionDetails")
@interface SessionDetails : NSObject
/// User id entered by the user when session is started.
@property (nonatomic, copy) NSString * _Nonnull userId;
/// Name of the project in MIRACL platform.
@property (nonatomic, copy) NSString * _Nonnull projectName;
/// URL of the project logo.
@property (nonatomic, copy) NSString * _Nonnull projectLogoURL;
/// Project id setting for the application in MIRACL platform.
@property (nonatomic, copy) NSString * _Nonnull projectId;
/// Client id setting for the application in MIRACL platform.
@property (nonatomic, copy) NSString * _Nonnull clientId;
/// Redirect URI setting for the application in MIRACL platform.
@property (nonatomic, copy) NSString * _Nonnull redirectURI;
/// Pin Length that needs to be entered from user.
@property (nonatomic) NSInteger pinLength;
@property (nonatomic) enum VerificationMethod verificationMethod;
@property (nonatomic, copy) NSString * _Nonnull verificationURL;
@property (nonatomic, copy) NSString * _Nonnull verificationCustomText;
@property (nonatomic, copy) NSString * _Nonnull identityTypeLabel;
@property (nonatomic) BOOL quickCodeEnabled;
@property (nonatomic) BOOL limitQuickCodeRegistration;
@property (nonatomic) enum IdentityType identityType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Object representing details from incoming authentication session.
SWIFT_CLASS("_TtC11MIRACLTrust28AuthenticationSessionDetails")
@interface AuthenticationSessionDetails : SessionDetails
/// Identifier of the authentication session.
@property (nonatomic, copy) NSString * _Nonnull accessId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Object that stores configurations of the SDK with values issued by MIRACL.
SWIFT_CLASS("_TtC11MIRACLTrust13Configuration")
@interface Configuration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol UserStorage;
@protocol Logger;
enum LoggingLevel : NSInteger;
@class NSURL;
@class NSURLSessionConfiguration;

/// Builds <a href="x-source-tag://Configuration">Configuration</a> objects.
SWIFT_CLASS_NAMED("Builder")
@interface ConfigurationBuilder : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWithProjectId:(NSString * _Nonnull)projectId clientId:(NSString * _Nonnull)clientId redirectURI:(NSString * _Nonnull)redirectURI OBJC_DESIGNATED_INITIALIZER;
/// Set custom <a href="x-source-tag://protocols-UserStorage">UserStorage</a> implementation.
/// \param userStorage custom <a href="x-source-tag://protocols-UserStorage">UserStorage</a>) implementation.
///
///
/// returns:
/// Configuration.Builder object.
- (ConfigurationBuilder * _Nonnull)userStorageWith:(id <UserStorage> _Nonnull)userStorage;
/// Set custom <a href="x-source-tag://protocols-Logger">Logger</a> writer implementation.
/// \param logger custom <a href="x-source-tag://protocols-Logger">Logger</a> implementation.
///
///
/// returns:
/// Configuration.Builder object.
- (ConfigurationBuilder * _Nonnull)loggerWith:(id <Logger> _Nonnull)logger;
/// Sets custom <a href="x-source-tag://enums-LoggingLevel">LoggingLevel</a> value. By default it is <code>off</code>.
/// This level can be set only for default logger, otherwise will be ignored.
/// \param level custom <a href="x-source-tag://enums-LoggingLevel">LoggingLevel</a>
///
///
/// returns:
/// Configuration.Builder object.
- (ConfigurationBuilder * _Nonnull)loggingLevelWith:(enum LoggingLevel)level;
/// Sets custom MIRACL platform URL.
/// \param url custom MIRACL platform URL.
///
///
/// returns:
/// Configuration.Builder object.
- (ConfigurationBuilder * _Nonnull)platformURLWith:(NSURL * _Nonnull)url;
/// Sets value of device name.
/// \param deviceName device name
///
///
/// returns:
/// Configuration.Builder object.
- (ConfigurationBuilder * _Nonnull)deviceNameWith:(NSString * _Nonnull)deviceName;
/// Use this when you want to set the custom configuration to the SDK’s instance of URLSession.
/// As a default value it uses <code>ephemeral</code> configuration, 30 seconds for <code>timeoutIntervalForRequest</code> and
/// 300 seconds for <code>timeoutIntervalForResource</code>.
/// \param urlSessionConfiguration configuration for the URLSession to be set.
///
///
/// returns:
/// Configuration.Builder object.
- (ConfigurationBuilder * _Nonnull)URLSessionConfigurationWith:(NSURLSessionConfiguration * _Nonnull)urlSessionConfiguration;
/// Returns <a href="x-source-tag://Configuration">Configuration</a> object.
///
/// throws:
/// <a href="x-source-tag://enums-ConfigurationError">ConfigurationError</a>.
///
/// returns:
/// <a href="x-source-tag://Configuration">Configuration</a> object.
- (Configuration * _Nullable)buildAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end

@class NSUUID;
@class NSData;

/// Representing a user’s identity in the system.
SWIFT_CLASS("_TtC11MIRACLTrust8Identity")
@interface Identity : NSObject
/// Identifier of the identity. It is used to be referenced in the storage.
@property (nonatomic, strong) NSUUID * _Nonnull uuid;
/// Actual representation of the identity.
@property (nonatomic, copy) NSData * _Nonnull mpinId;
/// The second factor of the authentication.
@property (nonatomic, copy) NSData * _Nonnull token;
/// Base64 encoded URL-s of DTA-s.
@property (nonatomic, copy) NSString * _Nonnull dtas;
/// The number of the digits the identity PIN should be.
@property (nonatomic) NSInteger pinLength;
/// The public part of the signing key.
@property (nonatomic, copy) NSData * _Nullable publicKey;
/// Hex encoded SHA256 representation of the mpinId property.
@property (nonatomic, readonly, copy) NSString * _Nonnull hashedMpinId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Possible identity types that can be used for identity verification.
typedef SWIFT_ENUM(NSInteger, IdentityType, open) {
  IdentityTypeEmail = 0,
  IdentityTypeAlphanumeric = 1,
};

/// Enums describing what are categories for logging into the SDK.
typedef SWIFT_ENUM(NSInteger, LogCategory, open) {
/// Logging into <code>configuration</code> category.
  LogCategoryConfiguration = 0,
/// Logging into <code>networking</code> category.
  LogCategoryNetworking = 1,
/// Logging into <code>crypto</code> category.
  LogCategoryCrypto = 2,
/// Logging into <code>registration</code> category.
  LogCategoryRegistration = 3,
/// Logging into <code>authentication</code> category.
  LogCategoryAuthentication = 4,
/// Logging into <code>signing</code> category.
  LogCategorySigning = 5,
/// Logging into <code>signing registration</code> category.
  LogCategorySigningRegistration = 6,
/// Logging into <code>verification</code> category.
  LogCategoryVerification = 7,
/// Logging into <code>verification</code> category.
  LogCategoryVerificationConfirmation = 8,
/// Logging into <code>storage</code> category.
  LogCategoryStorage = 9,
/// Logging into <code>Session Management</code> category.
  LogCategorySessionManagement = 10,
};


/// Protocol describing possible outputs for logging messages.
SWIFT_PROTOCOL("_TtP11MIRACLTrust6Logger_")
@protocol Logger
/// Outputs message with <code>debug</code> level.
/// \param message message that needs to be logged.
///
/// \param category which category of the SDK is the  logged message.
///
- (void)debugWithMessage:(NSString * _Nonnull)message category:(enum LogCategory)category;
/// Outputs message with <code>info</code> level.
/// \param message message that needs to be logged.
///
/// \param category which category of the SDK is the logged message.
///
- (void)infoWithMessage:(NSString * _Nonnull)message category:(enum LogCategory)category;
/// Outputs message with <code>warning</code> level.
/// \param message message that needs to be logged.
///
/// \param category which category of the SDK is the logged message.
///
- (void)warningWithMessage:(NSString * _Nonnull)message category:(enum LogCategory)category;
/// Outputs message with <code>error</code> level.
/// \param message message that needs to be logged.
///
/// \param category which category of the SDK is the logged message.
///
- (void)errorWithMessage:(NSString * _Nonnull)message category:(enum LogCategory)category;
@end

/// Enum describing on what level messages will be logged or logging will be turned off.
typedef SWIFT_ENUM(NSInteger, LoggingLevel, open) {
/// Logging is not allowed.
  LoggingLevelNone = 0,
/// Messages will be logged until the <code>debug</code> level.
  LoggingLevelDebug = 1,
/// Messages will be logged until the <code>info</code> level.
  LoggingLevelInfo = 2,
/// Messages will be logged until the <code>warning</code> level.
  LoggingLevelWarning = 3,
/// Messages will be logged until the <code>error</code> level.
  LoggingLevelError = 4,
};

@class User;
@class OTP;
@class QuickCode;
@class SigningSessionDetails;
@class Signature;
@class NSDate;
@class SigningSessionCompletionResult;

/// Main class of the SDK used for all possible actions like registration and authentication.
SWIFT_CLASS("_TtC11MIRACLTrust11MIRACLTrust")
@interface MIRACLTrust : NSObject
@property (nonatomic, copy) NSArray<User *> * _Nonnull users;
@property (nonatomic, copy) NSString * _Nonnull projectId;
/// Getting singleton instance of the MIRACLTrust class.
///
/// returns:
/// singleton instance of the MIRACLTrust class.
+ (MIRACLTrust * _Nonnull)getInstance SWIFT_WARN_UNUSED_RESULT;
/// Configure SDK with values issued by MIRACL and stored in the <a href="x-source-tag://Configuration">Configuration</a> object.
/// It is recommended to be called right after the application is launched.
/// \param configuration object storing configurations of the SDK.
///
+ (BOOL)configureWith:(Configuration * _Nonnull)configuration error:(NSError * _Nullable * _Nullable)error;
/// Set SDK project settings when they need to be updated after new session is established.
/// \param clientId <code>clientId</code> setting for the MIRACL Platform that needs to be updated.
///
/// \param projectId <code>projectId</code> setting for the MIRACL Platform that needs to be updated.
///
/// \param redirectURI <code>redirectURI</code> setting for the MIRACL Platform that needs to be updated.
///
- (BOOL)updateProjectSettingsWithProjectId:(NSString * _Nonnull)projectId clientId:(NSString * _Nonnull)clientId redirectURI:(NSString * _Nonnull)redirectURI error:(NSError * _Nullable * _Nullable)error;
/// Sending email for user id verification.
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     userId: identifier of the user identity. To verify identity this identifier needs to be valid email address.
///   </li>
///   <li>
///     authenticationSessionDetails: details for an authentication session.
///   </li>
///   <li>
///     completionHandler: a closure called when the verification has been completed. It can contain a flag indicating a verification result or an optional error object.
///   </li>
/// </ul>
- (void)sendVerificationEmailWithUserId:(NSString * _Nonnull)userId authenticationSessionDetails:(AuthenticationSessionDetails * _Nullable)authenticationSessionDetails completionHandler:(void (^ _Nonnull)(BOOL, NSError * _Nullable))completionHandler;
/// The method confirms user verification and as a result, an activation token is obtained. This activation token should be used in the registration process.
/// \param verificationURL a verification URL received as part of the verification process.
///
/// \param completionHandler a closure called when the verification has been confirmed. It can contain an optional ActivationTokenResponse object and an optional error object.
///
- (void)getActivationTokenWithVerificationURL:(NSURL * _Nonnull)verificationURL completionHandler:(void (^ _Nonnull)(ActivationTokenResponse * _Nullable, NSError * _Nullable))completionHandler;
/// Creates a new identity in the MIRACL platform.
/// \param userId an identifier of the user (e.g email address).
///
/// \param activationToken a token obtained during the user verification process indicating that the user has been already verified.
///
/// \param pushNotificationsToken current device push notifications token. This is used when push notifications for authentication
/// are enabled in the platform.
///
/// \param didRequestPinHandler a closure called when the PIN code is needed from the SDK. It can be used to show UI for entering the PIN code. Its parameter is another closure that is mandatory to be called after the user finishes their action.
///
/// \param completionHandler a closure called when creating a new identity has finished. It can contain an error object or the User where both of them are optional objects.
///
- (void)registerFor:(NSString * _Nonnull)userId activationToken:(NSString * _Nonnull)activationToken pushNotificationsToken:(NSString * _Nullable)pushNotificationsToken didRequestPinHandler:(void (^ _Nonnull)(void (^ _Nonnull)(NSString * _Nullable)))didRequestPinHandler completionHandler:(void (^ _Nonnull)(User * _Nullable, NSError * _Nullable))completionHandler;
/// Authenticates identity in the MIRACL platform.
/// Use this method to authenticate from your application.
/// This method generates so called <code>authCode</code>, which needs to be sent to a server for verification.
/// When verification is finished authentication is successful.
/// \param user object that keeps an authentication identity in it.
///
/// \param didRequestPinHandler a closure called when the PIN code is needed from the SDK. It can be used to show UI for entering the PIN code. Its parameter is another closure that is mandatory to be called after the user finishes their action.
///
/// \param completionHandler a closure called when the auth code is generated. It can contain an optional auth code string value or an optional error object.
///
- (void)authenticateWithUser:(User * _Nonnull)user didRequestPinHandler:(void (^ _Nonnull)(void (^ _Nonnull)(NSString * _Nullable)))didRequestPinHandler completionHandler:(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))completionHandler;
/// Authenticates identity in the MIRACL platform.
/// Use this method to authenticate another device or application with the usage of QR Code
/// presented on MIRACL login page.
/// \param user object that keeps an authentication identity in it.
///
/// \param qrCode a string read from the QR code.
///
/// \param didRequestPinHandler a closure called when the PIN code is needed from the SDK. It can be used to show UI for entering the PIN code. Its parameter is another closure that is mandatory to be called after the user finishes their action.
///
/// \param completionHandler a closure called when the identity is authenticated. It can contain a boolean flag representing the result of the authentication or an optional error object.
///
- (void)authenticateWithUser:(User * _Nonnull)user qrCode:(NSString * _Nonnull)qrCode didRequestPinHandler:(void (^ _Nonnull)(void (^ _Nonnull)(NSString * _Nullable)))didRequestPinHandler completionHandler:(void (^ _Nonnull)(BOOL, NSError * _Nullable))completionHandler;
/// Authenticates identity in the MIRACL platform.
/// Use this method when you want to authenticate another device or application with the usage of Push
/// notifications sent by a MIRACL platform.
/// \param payload payload dictionary received from push notification.
///
/// \param didRequestPinHandler a closure called when the PIN code is needed from the SDK. It can be used to show UI for entering the PIN code. Its parameter is another closure that is mandatory to be called after the user finishes their action.
///
/// \param completionHandler a closure called when the identity is authenticated. It can contain a boolean flag representing the result of the authentication or an optional error object.
///
- (void)authenticateWithPushNotificationPayload:(NSDictionary * _Nonnull)payload didRequestPinHandler:(void (^ _Nonnull)(void (^ _Nonnull)(NSString * _Nullable)))didRequestPinHandler completionHandler:(void (^ _Nonnull)(BOOL, NSError * _Nullable))completionHandler;
/// Authenticates identity in the MIRACL platform.
/// Use this method to authenticate another device or application with the usage of
/// Universal Link created by a MIRACL platform.
/// \param user object that keeps an authentication identity in it.
///
/// \param universalLinkURL universal link for authentication.
///
/// \param didRequestPinHandler a closure called when the PIN code is needed from the SDK. It can be used to show UI for entering the PIN code. Its parameter is another closure that is mandatory to be called after the user finishes their action.
///
/// \param completionHandler a closure called when the identity is authenticated. It can contain a boolean flag representing the result of the authentication or an optional error object.
///
- (void)authenticateWithUser:(User * _Nonnull)user universalLinkURL:(NSURL * _Nonnull)universalLinkURL didRequestPinHandler:(void (^ _Nonnull)(void (^ _Nonnull)(NSString * _Nullable)))didRequestPinHandler completionHandler:(void (^ _Nonnull)(BOOL, NSError * _Nullable))completionHandler;
/// Generate OTP against the MIRACL platform.
/// \param user an already registered user with authentication identity.
///
/// \param didRequestPinHandler a closure called when the PIN code is needed from the SDK. It can be used to show UI for entering the PIN code. Its parameter is another closure that is mandatory to be called after the user finishes their action.
///
/// \param completionHandler a closure called when the OTP  has been generated. It can contain a generated OTP object or an optional error object.
///
- (void)generateOTPWithUser:(User * _Nonnull)user didRequestPinHandler:(void (^ _Nonnull)(void (^ _Nonnull)(NSString * _Nullable)))didRequestPinHandler completionHandler:(void (^ _Nonnull)(OTP * _Nullable, NSError * _Nullable))completionHandler;
/// Generate QuickCode against the MIRACL platform.
/// \param user an already registered user with authentication identity.
///
/// \param didRequestPinHandler a closure called when the PIN code is needed from the SDK. It can be used to show UI for entering the PIN code. Its parameter is another closure that is mandatory to be called after the user finishes their action.
///
/// \param completionHandler a closure called when the QuickCode has been generated. It can contain a generated OTP object or an optional error object.
///
- (void)generateQuickCodeWithUser:(User * _Nonnull)user didRequestPinHandler:(void (^ _Nonnull)(void (^ _Nonnull)(NSString * _Nullable)))didRequestPinHandler completionHandler:(void (^ _Nonnull)(QuickCode * _Nullable, NSError * _Nullable))completionHandler;
/// Get <code>authentication</code> session details from MIRACL’s platform based on session identifier.
/// Use this method to get session details for application that tries to authenticate
/// against MIRACL Platform with the help of QR Code.
/// \param qrCode a string read from the QR code.
///
/// \param completionHandler a closure called when the authentication session details are fetched.It can contain a newly fetched authentication session details optional object
/// and an optional error object.
///
- (void)getAuthenticationSessionDetailsFromQRCodeWithQrCode:(NSString * _Nonnull)qrCode completionHandler:(void (^ _Nonnull)(AuthenticationSessionDetails * _Nullable, NSError * _Nullable))completionHandler;
/// Get <code>authentication</code> session details from MIRACL’s platform based on session identifier.
/// Use this method to get authentication session details for application that tries to authenticate
/// against MIRACL Platform with the help of Universal Link URL.
/// \param universalLinkURL universal link for authentication.
///
/// \param completionHandler a closure called when the authentication session details are fetched.It can contain a newly fetched authentication session details optional object
/// and an optional error object.
///
- (void)getAuthenticationSessionDetailsFromUniversalLinkURLWithUniversalLinkURL:(NSURL * _Nonnull)universalLinkURL completionHandler:(void (^ _Nonnull)(AuthenticationSessionDetails * _Nullable, NSError * _Nullable))completionHandler;
/// Get <code>authentication</code> session details from MIRACL’s platform based on session identifier.
/// Use this method to get authentication session details for application that tries to authenticate
/// against MIRACL Platform with the help of push notifications payload
/// \param pushNotificationPayload payload dictionary received from push notification.
///
/// \param completionHandler a closure called when the authentication session details are fetched.It can contain a newly fetched authentication session details optional object
/// and an optional error object.
///
- (void)getAuthenticationSessionDetailsFromPushNotificationPayloadWithPushNotificationPayload:(NSDictionary * _Nonnull)pushNotificationPayload completionHandler:(void (^ _Nonnull)(AuthenticationSessionDetails * _Nullable, NSError * _Nullable))completionHandler;
/// Cancel the authentication session by its <code>SessionDetails</code> object
/// \param authenticationSessionDetails details for authentication session, that is in progress.
///
/// \param completionHandler a closure called when the authentication session is aborted. It can contain a boolean flag representing the result of the abortion and an optional error object.
///
- (void)abortAuthenticationSessionWithAuthenticationSessionDetails:(AuthenticationSessionDetails * _Nonnull)authenticationSessionDetails completionHandler:(void (^ _Nonnull)(BOOL, NSError * _Nullable))completionHandler;
/// Get <code>signing</code> session details from MIRACL’s platform based on session identifier.
/// Use this method to get signing session details for application that tries to sign against MIRACL Platform with the usage of QR Code.
/// \param qrCode a string read from the QR code.
///
/// \param completionHandler a closure called when the session details are fetched.It can contain a newly fetched <code>signing</code> session details optional object
/// and an optional error object.
///
- (void)getSigningSessionDetailsFromQRCodeWithQrCode:(NSString * _Nonnull)qrCode completionHandler:(void (^ _Nonnull)(SigningSessionDetails * _Nullable, NSError * _Nullable))completionHandler;
/// Get <code>signing</code> session details from MIRACL’s platform based on session identifier.
/// Use this method to get signing session details for application that tries to sign against MIRACL Platform with the usage of Universal Link URL.
/// \param universalLinkURL universal link for signing.
///
/// \param completionHandler a closure called when the session details are fetched.It can contain a newly fetched <code>signing</code> session details optional object
/// and an optional error object.
///
- (void)getSigningSessionDetailsFromUniversalLinkURLWithUniversalLinkURL:(NSURL * _Nonnull)universalLinkURL completionHandler:(void (^ _Nonnull)(SigningSessionDetails * _Nullable, NSError * _Nullable))completionHandler;
/// Finish signing session with returning signature and its timestamp to the MIRACL Platform.
/// \param signingSessionDetails session that will be finished.
///
/// \param signature signature that needs to be sent to the server.
///
/// \param timestamp timestamp of the server.
///
/// \param completionHandler a closure called when the session is completed.It can contain a optional result of completion of <code>signing</code> session
/// and an optional error object.
///
- (void)completeSigningSessionWithSigningSessionDetails:(SigningSessionDetails * _Nonnull)signingSessionDetails signature:(Signature * _Nonnull)signature timestamp:(NSDate * _Nonnull)timestamp completionHandler:(void (^ _Nonnull)(SigningSessionCompletionResult * _Nullable, NSError * _Nullable))completionHandler;
/// Creates a new signing identity in the MIRACL platform.
/// \param user an already registered user with authentication identity.
///
/// \param didRequestAuthenticationPinHandler a closure called when the authentication identity PIN code is needed from the SDK. It can be used to show UI for entering the PIN code. Its parameter is another closure that is mandatory to be called after the user finishes their action.
///
/// \param didRequestSigningPinHandler a closure called when the signing identity PIN code is needed from the SDK. It can be used to show UI for entering the PIN code. Its parameter is another closure that is mandatory to be called after the user finishes their action.
///
/// \param completionHandler a closure called when the signing identity is created. It can contain a newly created signing identity optional object and an optional error object.
///
- (void)signingRegisterWithUser:(User * _Nonnull)user didRequestAuthenticationPinHandler:(void (^ _Nonnull)(void (^ _Nonnull)(NSString * _Nullable)))didRequestAuthenticationPinHandler didRequestSigningPinHandler:(void (^ _Nonnull)(void (^ _Nonnull)(NSString * _Nullable)))didRequestSigningPinHandler completionHandler:(void (^ _Nonnull)(User * _Nullable, NSError * _Nullable))completionHandler;
/// Create a cryptographic signature of a given document.
/// \param message the hash of a given document.
///
/// \param timestamp when the document has been signed.
///
/// \param user an already registered user with signing identity.
///
/// \param didRequestSigningPinHandler a closure called when the signing identity PIN code is needed from the SDK. It can be used to show UI for entering the PIN code. Its parameter is another closure that is mandatory to be called after the user finishes their action.
///
/// \param completionHandler a closure called when the signing has completed. It can contain a newly created Signature object or an optional error object.
///
- (void)signWithMessage:(NSData * _Nonnull)message timestamp:(NSDate * _Nonnull)timestamp user:(User * _Nonnull)user didRequestSigningPinHandler:(void (^ _Nonnull)(void (^ _Nonnull)(NSString * _Nullable)))didRequestSigningPinHandler completionHandler:(void (^ _Nonnull)(Signature * _Nullable, NSError * _Nullable))completionHandler;
/// Getting user by its project Id and its userId.
/// \param userId id of the user. Can be email or any other string.
///
/// \param projectId project id taken from the portal.
///
///
/// returns:
/// User object from the database. Returns nil if there is no such object in the storage.
- (User * _Nullable)getUserBy:(NSString * _Nonnull)userId projectId:(NSString * _Nullable)projectId SWIFT_WARN_UNUSED_RESULT;
/// Deletes a user from user storage with its signing and authentication identities.
/// \param user object that needs to be deleted.
///
- (BOOL)deleteWithUser:(User * _Nonnull)user error:(NSError * _Nullable * _Nullable)error;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC11MIRACLTrust11OneTimeCode")
@interface OneTimeCode : NSObject
@property (nonatomic, copy) NSString * _Nonnull code;
@property (nonatomic, copy) NSDate * _Nonnull nowTime;
@property (nonatomic, copy) NSDate * _Nonnull expireTime;
@property (nonatomic) NSInteger ttlSeconds;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11MIRACLTrust3OTP")
@interface OTP : OneTimeCode
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC11MIRACLTrust9QuickCode")
@interface QuickCode : OneTimeCode
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC11MIRACLTrust9Signature")
@interface Signature : NSObject
@property (nonatomic, copy) NSString * _Nonnull mpinId;
@property (nonatomic, copy) NSString * _Nonnull U;
@property (nonatomic, copy) NSString * _Nonnull V;
@property (nonatomic, copy) NSString * _Nonnull publicKey;
@property (nonatomic, copy) NSString * _Nonnull dtas;
@property (nonatomic, copy) NSString * _Nonnull signatureHash;
- (NSDictionary<NSString *, NSString *> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum SigningSessionStatus : NSInteger;

/// Result of  the completion of signing session.
SWIFT_CLASS("_TtC11MIRACLTrust30SigningSessionCompletionResult")
@interface SigningSessionCompletionResult : NSObject
/// Status of the signing session.
@property (nonatomic) enum SigningSessionStatus status;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Object representing details from incoming signing session.
SWIFT_CLASS("_TtC11MIRACLTrust21SigningSessionDetails")
@interface SigningSessionDetails : SessionDetails
/// Identifier of the signing session.
@property (nonatomic, copy) NSString * _Nonnull sessionId;
/// Hash of the transaction that needs to be signed.
@property (nonatomic, copy) NSString * _Nonnull signingHash;
/// Description of the transaction that needs to be signed.
@property (nonatomic, copy) NSString * _Nonnull signingDescription;
/// Status of the session.
@property (nonatomic) enum SigningSessionStatus status;
/// Date indicating if session is expired
@property (nonatomic, copy) NSDate * _Nonnull expireTime;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Enumeration describing status of the signing session.
typedef SWIFT_ENUM(NSInteger, SigningSessionStatus, open) {
  SigningSessionStatusActive = 0,
  SigningSessionStatusSigned = 1,
};



/// Representing user in the MIRACL platform.
/// This user is having authentication and signing identities.
SWIFT_CLASS("_TtC11MIRACLTrust4User")
@interface User : NSObject
/// Identifier of the user (e.g email address)
@property (nonatomic, copy) NSString * _Nonnull userId;
/// Identifier of the project in the MIRACL Trust platform.
@property (nonatomic, copy) NSString * _Nonnull projectId;
/// Identifier of the authentication identity.
@property (nonatomic, strong) NSUUID * _Nonnull authenticationIdentityId;
/// Identifier of the signing identity.
@property (nonatomic, strong) NSUUID * _Nullable signingIdentityId;
@property (nonatomic) BOOL revoked;
/// Retrieve last version of authentication Identity from the storage.
///
/// returns:
/// last version of authentication Identity.
- (Identity * _Nullable)getAuthenticationIdentity SWIFT_WARN_UNUSED_RESULT;
/// Retrieve last version of signing Identity from the storage.
///
/// returns:
/// last version of signing Identity.
- (Identity * _Nullable)getSigningIdentity SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// A type representing storage, where already the users will be kept between app launches. By default this SDK uses concrete implementation of the protocol done at <a href="x-source-tag://classes-SQLiteUserStorage">SQLiteUserStorage</a> class. Also keep in mind, that this protocol doesn’t provide any data encryption and therefore developers have to implement it by themselves.
SWIFT_PROTOCOL("_TtP11MIRACLTrust11UserStorage_")
@protocol UserStorage
/// Loads storage and its data into the memory.
- (BOOL)loadStorageAndReturnError:(NSError * _Nullable * _Nullable)error;
/// Adds a new user to the storage.
/// \param user a user that needs to be added to the storage.
///
- (BOOL)addWithUser:(User * _Nonnull)user error:(NSError * _Nullable * _Nullable)error;
/// Deletes the user from the storage.
/// \param user a user that needs to be deleted to the storage.
///
- (BOOL)deleteWithUser:(User * _Nonnull)user error:(NSError * _Nullable * _Nullable)error;
/// Updates the user in the storage
/// \param user a user that needs to be updated to the storage.
///
- (BOOL)updateWithUser:(User * _Nonnull)user error:(NSError * _Nullable * _Nullable)error;
/// Get all users written in the storage.
- (NSArray<User *> * _Nonnull)all SWIFT_WARN_UNUSED_RESULT;
/// Get User object by its user id and project id. If User isn’t present in the storage this method returns nil.
/// \param userId a user id to be checked in the storage.
///
/// \param projectId a project id to be checked in the storage.
///
- (User * _Nullable)getUserBy:(NSString * _Nonnull)userId projectId:(NSString * _Nonnull)projectId SWIFT_WARN_UNUSED_RESULT;
/// Getting identity by its identifier.
/// \param id identifier of the identity.
///
- (Identity * _Nullable)getIdentityBy:(NSUUID * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
/// Adding new identity to the storage.
/// \param identity identity object that will be written in the storage.
///
- (BOOL)addWithIdentity:(Identity * _Nonnull)identity error:(NSError * _Nullable * _Nullable)error;
/// Updates the identity object written in the storage.
/// \param identity identity object written in the storage.
///
- (BOOL)updateWithIdentity:(Identity * _Nonnull)identity error:(NSError * _Nullable * _Nullable)error;
@end

/// Possible verification methods that can be used for identity verification.
typedef SWIFT_ENUM(NSInteger, VerificationMethod, open) {
/// Custom identity verification, done with a client implementation.
  VerificationMethodFullCustom = 0,
/// Identity verification done by email.
  VerificationMethodStandardEmail = 1,
};

#endif
#if defined(__cplusplus)
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
